[project]
name = "domain-adaptation"
version = "0.1.0"
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "wandb",
    "weave",
    "hydra-core"
    "tqdm"
]

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"